name: deploy fuelwatch evidence website
on:
  push:
    branches: 
      - main
    paths:
      - pages/**/*
      - data/**/*
      - sources/**/*
      - .github/workflows/*.yaml
permissions:
  contents: read

env:
  DUCKDB_URL: https://github.com/duckdb/duckdb/releases/download/v1.0.0/duckdb_cli-linux-amd64.zip

jobs:
  makedb:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      
      - name: download duckdb
        run: |
          curl -L ${DUCKDB_URL} -o duckdb.zip
          unzip duckdb.zip -d duckdb
      
      - name: make fuelwatch database
        run: |
          export PATH=$PATH:$PWD/duckdb
          cd data
          ./get-data.sh
          ./make-db.sh ../sources/fuelwatch/fuelwatch.db

